name: kgsyks_destek
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.3.5+26 #MAJOR.MINOR.PATCH

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.2.0
  firebase_core: ^4.0.0
  flutter_native_splash: ^2.4.6
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  riverpod: ^3.0.0-dev.17
  flutter_riverpod: ^3.0.0-dev.17
  flutter_svg: ^2.2.0
  fl_chart: ^1.0.0
  sqflite: ^2.4.2

  path_provider: ^2.1.5
  path: ^1.9.1
  equatable: ^2.0.7
  google_fonts: ^6.3.1
  image_picker: ^1.1.0
  permission_handler: ^12.0.1
  firebase_crashlytics: ^5.0.1
  firebase_analytics: ^12.0.1
  flutter_image_compress: ^2.4.0
  firebase_app_check: ^0.4.0+1
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.1
  gap: ^3.0.1
  google_mlkit_text_recognition: ^0.15.0
  lottie: ^3.3.2
  flutter_gemini:
    git:
      url: https://github.com/AkhmadRamadani/flutter_gemini.git
      ref: master
  flutter_animate: ^4.5.2
  animated_text_kit: ^4.2.3
  connectivity_plus: ^7.0.0
  intl: ^0.20.2
  flutter_drawing_board: ^0.9.8
  share_plus: ^12.0.1
  timezone: ^0.10.1
  webview_flutter: ^4.13.0
  showcaseview: ^5.0.1
  shared_preferences: ^2.5.3
  google_mobile_ads: ^6.0.0
  tutorial_coach_mark: ^1.3.3
  app_tracking_transparency: ^2.0.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/Illustrations/
    - assets/images/
    - assets/icon/
    - assets/animations/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images    dart run flutter_native_splash:create --path=splash_screen.yaml

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#0B151F"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_foreground_inset: 24
  min_sdk_android: 21 # android min sdk min:16, default 21
  #remove_alpha_ios: true
